---
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9.7-node
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "package-lock.json" }}\
            -{{ .Environment.CACHE_VERSION }}
      - restore_cache:
          key: deps-{{ checksum "poetry.lock" }}\
            -{{ .Environment.CACHE_VERSION }}

      - run:
          name: python module install
          command: |
            make -j $(nproc) setup setup-cc

      - save_cache:
          key: cache-{{ checksum "package-lock.json" }}\
            -{{ .Environment.CACHE_VERSION }}
          paths:
            - ./node_modules
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}\
            -{{ .Environment.CACHE_VERSION }}
          paths:
            - ~/.cache/pypoetry/virtualenvs
            - ~/.local/bin-cc

      - run:
          name: Lint
          command: |
            poetry run make -j $(nproc) lint

      - run:
          name: Test Python codes
          command: |
            poetry run make -j $(nproc) test-cc

      - store_artifacts:
          path: htmlcov

workflows:
  version: 2
  build:
    jobs:
      - build
